name: Docker Image CI

on:
  push:
    branches:
    - Main
    - development
  pull_request:
    branches:
    - Main
    - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_NAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u ${{secrets.DOCKER_NAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker Image
      # run: docker build . --file Dockerfile --tag metalman66/cicd-test:$(date + %s)
      run: |
        docker build -t ${{secrets.DOCKER_NAME}}/cicd-test:arm64 .
        docker build -t ${{secrets.DOCKER_NAME}}/cicd-test:amd64 .
    
    - name: Docker Push
      run: |
        docker push ${{secrets.DOCKER_NAME}}/cicd-test:arm64
        docker push ${{secrets.DOCKER_NAME}}/cicd-test:amd64

