name: CICD

on:
  push:
    branches:
    - Main
    - development
  pull_request:
    branches:
    - Main
    - development

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:latest
    #     env:
    #       POSTGRES_DB: demo_db     
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_USER: postgres
    #     ports:
    #       - 5432:5432
      
    steps:
    - uses: actions/checkout@v2
    - name: Installing expect and connecting to ssh
      run : |
        sudo apt install expect
        expect -c 'spawn ssh exouser@149.165.152.101;expect "connecting"; send "yes\r";expect "password:";send "${{secrets.PASSPHRASE}}\r"; interact'
        exit
        sudo touch file_2.txt
      # - uses: actions/checkout@v3
      
      # - name: Configure SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "$SSH_KEY" > ~/.ssh/staging.key
      #     chmod 600 ~/.ssh/staging.key
      #     cat >>~/.ssh/config <<END
      #     Host deploy
      #       HostName $SSH_HOST
      #       User $SSH_USER
      #       IdentityFile ~/.ssh/staging.key
      #       StrictHostKeyChecking no
      #     END
      #   env:
      #     SSH_KEY: ${{ secrets.DEPLOY_PUBLIC_KEY }}
      #     SSH_HOST: 149.165.152.101
      #     SSH_USER: exouser
          
      # - name: run the deployment script
      #   run: |
      #        SCRIPT="sudo touch file_2.txt"
      #        ssh deploy "${SCRIPT}"
             

        

    
    # - name: Setup Go
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: '1.17.6' 

    # - name: Install dependencies
    #   run: | 
    #     go version
    #     go mod tidy
    #     go build
    
    # - name: Creating ENV file
    #   run: cat example.env >> .env

    # - name: Build
    #   run: |
    #     go build .


    # # Building Docker Image
    # - name: Docker Login
    #   env:
    #     DOCKER_USER: '${{secrets.DOCKER_USERNAME}}'
    #     DOCKER_PASSWORD: '${{secrets.DOCKER_PASSWORD}}'
    #   run: |
    #     docker login -u '${{secrets.DOCKER_USERNAME}}' -p '${{secrets.DOCKER_PASSWORD}}'
        
    # - name: Build the Docker Image
    #   # run: docker build . --file Dockerfile --tag metalman66/cicd-test:$(date + %s)
    #   run: |
    #     docker build . --file Dockerfile --tag tanukansaldocker123/cicd-test:amd64
    #     docker build . --file Dockerfile --tag tanukansaldocker123/cicd-test:arm64
    #   # run: |
    #   #   docker build -t '${{ secrets.DOCKER_USERNAME }}'/cicd-test:arm64 .
    #   #   docker build -t '${{ secrets.DOCKER_USERNAME }}'/cicd-test:amd64 .

    # - name: Docker Push
    #   run: |
    #     docker push tanukansaldocker123/cicd-test:amd64
    #     docker push tanukansaldocker123/cicd-test:arm64
    #   # docker push '${{secrets.DOCKER_USERNAME}}'/cicd-test:arm64